//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeProjectDemo.DataModel
{
    using System;
    using System.Collections.Generic;
    using Model;
    
    public partial class Product : IBaseTable
    {
        public int Id { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string Name { get; set; }
    }
}
